masterplus/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('myapp.urls')),
]

myapp/urls.py
# myapp/urls.py

from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('register/', views.register, name='register'),
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('new/', views.request_create, name='request_create'),
    path('edit/<int:pk>/', views.request_update, name='request_update'),
    path('delete/<int:pk>/', views.request_delete, name='request_delete'),
    path('take/<int:pk>/', views.request_take, name='request_take'),
    path('assign/<int:pk>/', views.request_assign, name='request_assign'),  # Добавленный URL
    path('profile/edit/', views.profile_edit, name='profile_edit'),
    path('ajax/load-repair-types/', views.ajax_load_repair_types, name='ajax_load_repair_types'),
    path('ajax/load-repair-details/', views.ajax_load_repair_details, name='ajax_load_repair_details'),
    path('assign/<int:pk>/', views.request_assign, name='request_assign'),
    path('profile/change_password/', views.change_password, name='change_password'),
    path('request/<int:pk>/view/', views.request_view, name='request_view'),
    path('request/<int:pk>/edit/', views.request_update, name='request_update'),
]

myapp/models.py
from django.db import models
from django.contrib.auth.models import User
from django.contrib.auth.models import AbstractUser
from django.conf import settings
from django.contrib.contenttypes.models import ContentType
from django.utils.translation import gettext_lazy as _
class Street(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

class RepairType(models.Model):
    CATEGORY_CHOICES = [
        ('small_repair', 'Мелкий ремонт'),
        ('sub_work', 'Подсобные работы'),
        ('warehouse', 'Склад'),
    ]

    name = models.CharField(max_length=100)
    category = models.CharField(max_length=20, choices=CATEGORY_CHOICES)
    description = models.TextField(blank=True, null=True)

    def __str__(self):
        return self.name

class RepairDetail(models.Model):
    repair_type = models.ForeignKey(RepairType, on_delete=models.CASCADE)
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

class Request(models.Model):
    STATUS_CHOICES = [
        ('new', 'Новый'),
        ('in_progress', 'В процессе'),
        ('completed', 'Завершено'),
        ('closed', 'Закрыто'),
    ]

    CATEGORY_CHOICES = [
        ('small_repair', 'Мелкий ремонт'),
        ('sub_work', 'Подсобные работы'),
        ('warehouse', 'Склад'),
    ]
    IMPORTANCE_CHOICES = [
        ('low', 'Низкая'),
        ('medium', 'Средняя'),
        ('high', 'Высокая'),
    ]
    importance = models.CharField(max_length=10, choices=IMPORTANCE_CHOICES, default='medium')

    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, null=True, blank=True)
    category = models.CharField(max_length=20, choices=CATEGORY_CHOICES, default='small_repair')
    primary_repair_type = models.ForeignKey(RepairType, on_delete=models.SET_NULL, null=True, blank=True, related_name='primary_requests')
    secondary_repair_type = models.ForeignKey(RepairDetail, on_delete=models.SET_NULL, null=True, blank=True, related_name='secondary_requests')
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)
    middle_name = models.CharField(max_length=30, blank=True, null=True)
    short_description = models.CharField(max_length=100)
    street = models.ForeignKey(Street, on_delete=models.CASCADE, null=True, blank=True)
    building = models.CharField(max_length=10, null=True, blank=True)
    room = models.CharField(max_length=10, null=True, blank=True)
    contact_phone = models.CharField(max_length=20)
    email = models.EmailField()
    description = models.TextField()
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default='new')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    assigned_performer = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True, blank=True, related_name='assigned_requests')
    performer = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True, blank=True, related_name='performed_requests')

    def __str__(self):
        return f'{self.last_name} {self.first_name} - {self.category}'


class User(AbstractUser):
    CATEGORY_CHOICES = [
        ('small_repair', 'Мелкий ремонт'),
        ('sub_work', 'Подсобные работы'),
        ('warehouse', 'Склад'),
    ]

    middle_name = models.CharField(max_length=30, blank=True, null=True, verbose_name='Отчество')
    phone_number = models.CharField(max_length=20, blank=True, null=True, verbose_name='Номер телефона')
    category = models.CharField(max_length=20, choices=CATEGORY_CHOICES, null=True, blank=True, verbose_name='Категория')
    groups = models.ManyToManyField(
        'auth.Group',
        related_name='custom_user_set',
        blank=True,
        help_text='The groups this user belongs to.',
        verbose_name='groups',
    )
    user_permissions = models.ManyToManyField(
        'auth.Permission',
        related_name='custom_user_permissions_set',
        blank=True,
        help_text='Specific permissions for this user.',
        verbose_name='user permissions',
    )

class AdminLog(models.Model):
    action_time = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    content_type = models.ForeignKey(ContentType, on_delete=models.SET_NULL, null=True, blank=True)
    object_id = models.TextField(blank=True, null=True)
    object_repr = models.CharField(max_length=200)
    action_flag = models.PositiveSmallIntegerField()
    change_message = models.TextField(blank=True)

    class Meta:
        verbose_name = _("log entry")
        verbose_name_plural = _("log entries")

    def __str__(self):
        return self.object_repr

    created_at = models.DateTimeField(default=timezone.now, verbose_name=_("Дата создания"))

myapp/forms.py
from django import forms
from .models import Request, Street, RepairType, RepairDetail, User
#from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, UserChangeForm, AuthenticationForm
import logging

logger = logging.getLogger(__name__)

class RequestForm(forms.ModelForm):
    no_middle_name = forms.BooleanField(required=False, label='Нет отчества', widget=forms.CheckboxInput(attrs={'class': 'form-check-input'}))

    class Meta:
        model = Request
        fields = [
            'category', 'primary_repair_type', 'secondary_repair_type', 'first_name',
            'last_name', 'middle_name', 'no_middle_name', 'short_description', 'street', 'building',
            'room', 'contact_phone', 'email', 'description'
        ]
        labels = {
            'category': 'Категория',
            'primary_repair_type': 'Вид ремонта',
            'secondary_repair_type': 'Подробности',
            'first_name': 'Имя',
            'last_name': 'Фамилия',
            'middle_name': 'Отчество',
            'no_middle_name': 'Нет отчества',
            'short_description': 'Краткое описание проблемы',
            'street': 'Улица',
            'building': 'Здание',
            'room': 'Помещение',
            'contact_phone': 'Контактный телефон',
            'email': 'Адрес электронной почты',
            'description': 'Описание проблемы',
        }
        widgets = {
            'category': forms.Select(attrs={'class': 'form-control'}),
            'primary_repair_type': forms.Select(attrs={'class': 'form-control'}),
            'secondary_repair_type': forms.Select(attrs={'class': 'form-control'}),
            'first_name': forms.TextInput(attrs={'class': 'form-control'}),
            'last_name': forms.TextInput(attrs={'class': 'form-control'}),
            'middle_name': forms.TextInput(attrs={'class': 'form-control'}),
            'short_description': forms.TextInput(attrs={'class': 'form-control'}),
            'street': forms.Select(attrs={'class': 'form-control'}),
            'building': forms.TextInput(attrs={'class': 'form-control'}),
            'room': forms.TextInput(attrs={'class': 'form-control'}),
            'contact_phone': forms.TextInput(attrs={'class': 'form-control', 'id': 'id_contact_phone'}),
            'email': forms.EmailInput(attrs={'class': 'form-control'}),
            'description': forms.Textarea(attrs={'class': 'form-control'}),
        }

    def __init__(self, *args, **kwargs):
        category = kwargs.pop('category', None)
        super().__init__(*args, **kwargs)

        # Set required fields
        self.fields['category'].required = True
        self.fields['primary_repair_type'].required = True
        self.fields['first_name'].required = True
        self.fields['last_name'].required = True
        self.fields['short_description'].required = True
        self.fields['street'].required = True
        self.fields['building'].required = True
        self.fields['room'].required = True
        self.fields['contact_phone'].required = True
        self.fields['email'].required = True

        # Non-required fields
        self.fields['middle_name'].required = False
        self.fields['description'].required = False
        self.fields['secondary_repair_type'].required = False

        self.fields['street'].queryset = Street.objects.all()
        self.fields['street'].empty_label = None

        if category:
            self.fields['primary_repair_type'].queryset = RepairType.objects.filter(category=category)
        else:
            self.fields['primary_repair_type'].queryset = RepairType.objects.none()

        self.fields['secondary_repair_type'].queryset = RepairDetail.objects.none()

        if 'primary_repair_type' in self.data:
            try:
                repair_type_id = int(self.data.get('primary_repair_type'))
                self.fields['secondary_repair_type'].queryset = RepairDetail.objects.filter(
                    repair_type_id=repair_type_id).order_by('name')
            except (ValueError, TypeError):
                pass
        elif self.instance.pk and self.instance.primary_repair_type:
            self.fields['secondary_repair_type'].queryset = self.instance.primary_repair_type.repairdetail_set.order_by(
                'name')

    def clean(self):
        cleaned_data = super().clean()
        primary_repair_type = cleaned_data.get('primary_repair_type')
        secondary_repair_type = cleaned_data.get('secondary_repair_type')
        middle_name = cleaned_data.get('middle_name')
        no_middle_name = cleaned_data.get('no_middle_name')

        if primary_repair_type and RepairDetail.objects.filter(repair_type=primary_repair_type).exists() and not secondary_repair_type:
            self.add_error('secondary_repair_type', 'This field is required.')

        # Обработка поля отчества и флага "Нет отчества"
        if no_middle_name:
            cleaned_data['middle_name'] = ''
            self.fields['middle_name'].required = False
        elif not middle_name:
            self.add_error('middle_name', 'Это поле обязательно, если не указано "Нет отчества".')

        return cleaned_data

class UserRegForm(UserCreationForm):
    first_name = forms.CharField(required=True, label='Имя', widget=forms.TextInput(attrs={'class': 'form-control'}))
    last_name = forms.CharField(required=True, label='Фамилия', widget=forms.TextInput(attrs={'class': 'form-control'}))
    middle_name = forms.CharField(required=True, label='Отчество', widget=forms.TextInput(attrs={'class': 'form-control'}))
    no_middle_name = forms.BooleanField(required=False, label='Нет отчества', widget=forms.CheckboxInput(attrs={'class': 'form-check-input'}))
    phone_number = forms.CharField(required=True, label='Номер телефона', widget=forms.TextInput(attrs={'class': 'form-control'}))
    email = forms.EmailField(required=True, label='Электронная почта', widget=forms.EmailInput(attrs={'class': 'form-control'}))

    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'middle_name', 'no_middle_name', 'phone_number', 'email', 'password1', 'password2']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        if 'no_middle_name' in self.data and self.data['no_middle_name'] == 'on':
            self.fields['middle_name'].required = False

    def clean(self):
        cleaned_data = super().clean()
        middle_name = cleaned_data.get('middle_name')
        no_middle_name = cleaned_data.get('no_middle_name')

        if no_middle_name:
            cleaned_data['middle_name'] = ''
            self.fields['middle_name'].required = False
        elif not middle_name:
            self.add_error('middle_name', 'Это поле обязательно, если не указано "Нет отчества".')

        return cleaned_data

"""class UserRegForm(UserCreationForm):
    CATEGORY_CHOICES = [
        ('small_repair', 'Мелкий ремонт'),
        ('sub_work', 'Подсобные работы'),
        ('warehouse', 'Склад'),
    ]

    middle_name = forms.CharField(required=False, label='Отчество', widget=forms.TextInput(attrs={'class': 'form-control'}))
    phone_number = forms.CharField(required=False, label='Номер телефона', widget=forms.TextInput(attrs={'class': 'form-control'}))
    category = forms.ChoiceField(choices=CATEGORY_CHOICES, label='Категория', required=False, widget=forms.Select(attrs={'class': 'form-control'}))

    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'middle_name', 'phone_number', 'category', 'password1', 'password2']
"""

class CustomUserChangeForm(UserChangeForm):
    CATEGORY_CHOICES = [
        ('small_repair', 'Мелкий ремонт'),
        ('sub_work', 'Подсобные работы'),
        ('warehouse', 'Склад'),
    ]

    middle_name = forms.CharField(required=False, label='Отчество', widget=forms.TextInput(attrs={'class': 'form-control'}))
    no_middle_name = forms.BooleanField(required=False, label='Нет отчества', widget=forms.CheckboxInput(attrs={'class': 'form-check-input'}))
    phone_number = forms.CharField(required=False, label='Номер телефона', widget=forms.TextInput(attrs={'class': 'form-control'}))
    category = forms.ChoiceField(required=False, choices=CATEGORY_CHOICES, label='Категория', widget=forms.Select(attrs={'class': 'form-control'}))
    first_name = forms.CharField(required=True, label='Имя', widget=forms.TextInput(attrs={'class': 'form-control'}))
    last_name = forms.CharField(required=True, label='Фамилия', widget=forms.TextInput(attrs={'class': 'form-control'}))
    email = forms.EmailField(required=True, label='Электронная почта', widget=forms.EmailInput(attrs={'class': 'form-control'}))
    username = forms.CharField(required=True, label='Имя пользователя', widget=forms.TextInput(attrs={'class': 'form-control'}))

    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'middle_name', 'no_middle_name', 'phone_number', 'category', 'email']

    def __init__(self, *args, **kwargs):
        user = kwargs.pop('user', None)  # Получаем текущего пользователя
        super().__init__(*args, **kwargs)

        # Устанавливаем видимость поля "Категория" только для операторов
        if user and user.groups.filter(name='Оператор').exists() and not user.is_superuser:
            self.fields['category'].widget.attrs['style'] = 'display:block;'
        else:
            self.fields['category'].widget.attrs['style'] = 'display:none;'

        if not self.instance.middle_name:
            self.fields['no_middle_name'].initial = True
            self.fields['middle_name'].required = False

    def clean(self):
        cleaned_data = super().clean()
        middle_name = cleaned_data.get('middle_name')
        no_middle_name = cleaned_data.get('no_middle_name')

        if no_middle_name:
            cleaned_data['middle_name'] = ''
            self.fields['middle_name'].required = False

myapp/templates/myapp/change_password.html
{% load custom_tags %}
<!DOCTYPE html>
<html>
<head>
    <title>Изменение пароля</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <style>
        .alert-error {
            color: #721c24;
            background-color: #f8d7da;
            border-color: #f5c6cb;
        }
        .alert {
            width: 100%;
        }
    </style>
</head>
<body>
    <div class="container">
        <div class="d-flex justify-content-between align-items-center mt-5">
            <h1>Изменение пароля</h1>
            <div class="dropdown">
                <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Меню
                </button>
                <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                    <a class="dropdown-item" href="{% url 'profile_edit' %}">Редактирование профиля</a>
                    <a class="dropdown-item" href="{% url 'change_password' %}">Изменение пароля</a>
                </div>
            </div>
        </div>
        {% if messages %}
        <div class="mt-3">
            {% for message in messages %}
            <div class="alert {% if message.tags == 'error' %}alert-error{% else %}alert-{{ message.tags }}{% endif %}">{{ message }}</div>
            {% endfor %}
        </div>
        {% endif %}
        <form method="post">
            {% csrf_token %}
            <div class="form-group">
                <label for="id_old_password">Старый пароль</label>
                {{ password_form.old_password|add_class:"form-control" }}
            </div>
            <div class="form-group">
                <label for="id_new_password1">Новый пароль</label>
                {{ password_form.new_password1|add_class:"form-control" }}
            </div>
            <div class="form-group">
                <label for="id_new_password2">Подтверждение нового пароля</label>
                {{ password_form.new_password2|add_class:"form-control" }}
            </div>
            <button type="submit" class="btn btn-primary">Изменить пароль</button>
            <a href="{% url 'dashboard' %}" class="btn btn-secondary">Отмена</a>
        </form>
    </div>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
</body>
</html>

myapp/templates/myapp/repair_detail_dropdown_list_options.html
<option value="" disabled selected hidden>Выберите тип работ</option>
{% for repair_detail in repair_details %}
<option value="{{ repair_detail.id }}">{{ repair_detail.name }}</option>
{% endfor %}

myapp/templates/myapp/repair_type_dropdown_list_options.html
<option value="" disabled selected hidden>Выберите вид ремонта</option>
{% for repair_type in repair_types %}
<option value="{{ repair_type.id }}">{{ repair_type.name }}</option>
{% endfor %}

myapp/templates/myapp/request_form.html
{% load custom_tags %}
<!DOCTYPE html>
<html>
<head>
    <title>Форма заявки</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.inputmask/5.0.7-beta.17/jquery.inputmask.min.js"></script>
    <style>
        .error-glow {
            box-shadow: 0 0 5px red;
        }
        .alert-error {
            color: #721c24;
            background-color: #f8d7da;
            border-color: #f5c6cb;
        }
        .alert {
            width: 100%;
        }
    </style>
</head>
<body>
    <div class="container">
        <h1 class="mt-5">Форма заявки</h1>
        {% if messages %}
        <div class="mt-3">
            {% for message in messages %}
            <div class="alert {% if message.tags == 'error' %}alert-error{% else %}alert-{{ message.tags }}{% endif %}">{{ message }}</div>
            {% endfor %}
        </div>
        {% endif %}
        <form method="post" novalidate id="requestForm">
            {% csrf_token %}
            <div class="form-group">
                <label for="id_category">Категория</label>
                {{ form.category }}
                <input type="hidden" id="hidden_category" name="category" value="{{ form.category.value }}">
                {% if form.category.errors %}
                    <div class="invalid-feedback d-block">{{ form.category.errors }}</div>
                {% endif %}
            </div>
            <div class="form-group">
                <label for="id_last_name">Фамилия</label>
                {{ form.last_name|add_class:"form-control" }}
                {% if form.last_name.errors %}
                    <div class="invalid-feedback d-block">{{ form.last_name.errors }}</div>
                {% endif %}
            </div>
            <div class="form-group">
                <label for="id_first_name">Имя</label>
                {{ form.first_name|add_class:"form-control" }}
                {% if form.first_name.errors %}
                    <div class="invalid-feedback d-block">{{ form.first_name.errors }}</div>
                {% endif %}
            </div>
            <div class="form-group">
                <label for="id_middle_name">Отчество</label>
                {{ form.middle_name|add_class:"form-control" }}
                <div class="form-check mt-2">
                    {{ form.no_middle_name|add_class:"form-check-input" }}
                    <label class="form-check-label" for="id_no_middle_name">Нет отчества</label>
                </div>
                {% if form.middle_name.errors %}
                    <div class="invalid-feedback d-block">{{ form.middle_name.errors }}</div>
                {% endif %}
            </div>
            <div class="form-group">
                <label for="id_contact_phone">Контактный телефон</label>
                {{ form.contact_phone|add_class:"form-control" }}
                {% if form.contact_phone.errors %}
                    <div class="invalid-feedback d-block">{{ form.contact_phone.errors }}</div>
                {% endif %}
            </div>
            <div class="form-group">
                <label for="id_street">Улица</label>
                <select id="id_street" name="street" class="form-control" required>
                    <option value="" disabled selected hidden></option>
                    {% for street in form.fields.street.queryset %}
                    <option value="{{ street.id }}" {% if form.instance.street and street.id == form.instance.street.id %}selected{% endif %}>{{ street.name }}</option>
                    {% endfor %}
                </select>
                {% if form.street.errors %}
                    <div class="invalid-feedback d-block">{{ form.street.errors }}</div>
                {% endif %}
            </div>
            <div class="form-group">
                <label for="id_building">Здание</label>
                {{ form.building|add_class:"form-control" }}
                {% if form.building.errors %}
                    <div class="invalid-feedback d-block">{{ form.building.errors }}</div>
                {% endif %}
            </div>
            <div class="form-group">
                <label for="id_room">Помещение</label>
                {{ form.room|add_class:"form-control" }}
                {% if form.room.errors %}
                    <div class="invalid-feedback d-block">{{ form.room.errors }}</div>
                {% endif %}
            </div>
            <div class="form-group">
                <label for="id_email">Адрес электронной почты</label>
                {{ form.email|add_class:"form-control" }}
                {% if form.email.errors %}
                    <div class="invalid-feedback d-block">{{ form.email.errors }}</div>
                {% endif %}
            </div>
            <div class="form-group">
                <label for="id_primary_repair_type">Вид ремонта</label>
                <select id="id_primary_repair_type" name="primary_repair_type" class="form-control" required>
                    <option value="" disabled selected hidden>Выберите вид ремонта</option>
                </select>
                {% if form.primary_repair_type.errors %}
                    <div class="invalid-feedback d-block">{{ form.primary_repair_type.errors }}</div>
                {% endif %}
                <select id="id_secondary_repair_type" name="secondary_repair_type" class="form-control mt-2" disabled>
                </select>
                {% if form.secondary_repair_type.errors %}
                    <div class="invalid-feedback d-block">{{ form.secondary_repair_type.errors }}</div>
                {% endif %}
            </div>
            <div class="form-group">
                <label for="id_short_description">Краткое описание проблемы</label>
                {{ form.short_description|add_class:"form-control" }}
                {% if form.short_description.errors %}
                    <div class="invalid-feedback d-block">{{ form.short_description.errors }}</div>
                {% endif %}
            </div>
            <div class="form-group">
                <label for="id_description">Описание проблемы</label>
                {{ form.description|add_class:"form-control" }}
            </div>
            <div class="form-buttons">
                <button type="submit" class="btn btn-primary">
                    {% if form.instance.pk %}
                        Сохранить
                    {% else %}
                        Отправить
                    {% endif %}
                </button>
                <a href="{% if form.instance.pk %}{% url 'dashboard' %}{% else %}{% url 'index' %}{% endif %}" class="btn btn-secondary">Отмена</a>
            </div>
        </form>
    </div>
    <script>
        $(document).ready(function() {
            $("#id_contact_phone").inputmask("+7 (999) 999-99-99");

            function updateRepairTypeOptions(category, initial) {
                $.ajax({
                    url: '{% url "ajax_load_repair_types" %}',
                    data: {
                        'category': category
                    },
                    success: function (data) {
                        $("#id_primary_repair_type").html('<option value="" disabled selected hidden>Выберите вид ремонта</option>' + data);
                        if (initial) {
                            $("#id_primary_repair_type").val(initial).change();
                        } else {
                            $("#id_secondary_repair_type").html('').prop('disabled', true);
                        }
                    }
                });
            }

            function updateRepairDetailOptions(repair_type_id, initial) {
                $.ajax({
                    url: '{% url "ajax_load_repair_details" %}',
                    data: {
                        'repair_type_id': repair_type_id
                    },
                    success: function (data) {
                        if (data.trim() === '') {
                            $("#id_secondary_repair_type").html('').prop('disabled', true).prop('required', false);
                        } else {
                            $("#id_secondary_repair_type").html('<option value="" disabled selected hidden>Выберите подробности ремонта</option>' + data).prop('disabled', false).prop('required', true);
                            if (initial) {
                                $("#id_secondary_repair_type").val(initial);
                            }
                        }
                    }
                });
            }

            var initialCategory = $("#id_category").val();
            var initialPrimaryRepairType = "{{ form.instance.primary_repair_type.id }}";
            var initialSecondaryRepairType = "{{ form.instance.secondary_repair_type.id }}";

            if (initialCategory) {
                updateRepairTypeOptions(initialCategory, initialPrimaryRepairType);
            }

            $("#id_category").change(function () {
                var category = $(this).val();
                $("#hidden_category").val(category);
                updateRepairTypeOptions(category);
                $("#id_secondary_repair_type").html('').prop('disabled', true).prop('required', false);
            });

            $("#id_primary_repair_type").change(function () {
                var repair_type_id = $(this).val();
                updateRepairDetailOptions(repair_type_id, initialSecondaryRepairType);
            });

            // Initial load for editing existing form
            if ($("#id_primary_repair_type").val()) {
                updateRepairDetailOptions($("#id_primary_repair_type").val(), initialSecondaryRepairType);
            }

            // Toggle middle name field
            function toggleMiddleNameField() {
                if ($('#id_no_middle_name').is(':checked')) {
                    $('#id_middle_name').prop('disabled', true).val('').removeClass('error-glow');
                } else {
                    $('#id_middle_name').prop('disabled', false);
                }
            }

            $('#id_no_middle_name').change(function() {
                toggleMiddleNameField();
            });

            toggleMiddleNameField();  // Ensure correct state on page load

            // Highlight fields with errors on form submit
            $('#requestForm').on('submit', function() {
                var isValid = true;
                var middleNameField = $('#id_middle_name');
                var noMiddleNameChecked = $('#id_no_middle_name').is(':checked');

                // Проверка для поля отчества
                if (!middleNameField.val() && !noMiddleNameChecked) {
                    middleNameField.addClass('error-glow');
                    isValid = false;
                } else {
                    middleNameField.removeClass('error-glow');
                }

                // Общая проверка для всех обязательных полей
                $(this).find(':input[required]').each(function() {
                    if (!this.value) {
                        $(this).addClass('error-glow');
                        isValid = false;
                    } else {
                        $(this).removeClass('error-glow');
                    }
                });

                if (!isValid) {
                    $('#errorMessage').remove();
                    $('<div id="errorMessage" class="alert alert-error mt-3">Не все обязательные поля заполнены!</div>').insertAfter('h1');
                    $('html, body').animate({ scrollTop: 0 }, 'slow');
                }
                return isValid;
            });

            // Remove highlight on input change
            $(this).find(':input').on('input', function() {
                if (this.value) {
                    $(this).removeClass('error-glow');
                }
            });
        });
    </script>
</body>
</html>